#spring.application.name=movieApi
spring:
  datasource:
    username: admin
    password: Zxcvbnm
    url: jdbc:postgres://172.17.0.2:5432/movies
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true